<?php
namespace App\Enum;

enum CreditTransactionReason: string
{
    case BONUS_INSCRIPTION = 'BONUS_INSCRIPTION';
    case PAIEMENT_RESERVATION = 'PAIEMENT_RESERVATION';
    case COMMISSION_PLATEFORME = 'COMMISSION_PLATEFORME';
    case PAIEMENT_CONDUCTEUR = 'PAIEMENT_CONDUCTEUR';
    case REMBOURSEMENT = 'REMBOURSEMENT';
    case AJUSTEMENT_ADMIN = 'AJUSTEMENT_ADMIN';
}
?>